In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Health_Risk_Dataset.csv')
df

,Patient_ID,Respiratory_Rate,Oxygen_Saturation,O2_Scale,Systolic_BP,Heart_Rate,Temperature,Consciousness,On_Oxygen,Risk_Level
0,P0522,25,96,1,97,107,37.5,A,0,Medium
1,P0738,28,92,2,116,151,38.5,P,1,High
2,P0741,29,91,1,79,135,38.4,A,0,High
3,P0661,24,96,1,95,92,37.3,A,0,Medium
4,P0412,20,96,1,97,97,37.4,A,0,Low
...,...,...,...,...,...,...,...,...,...,...
995,P0107,18,96,1,124,72,37.2,A,0,Normal
996,P0271,19,95,1,129,70,38.1,A,0,Low
997,P0861,39,82,1,101,137,37.5,A,1,High
998,P0436,15,92,1,106,108,38.6,A,0,Medium
999,P0103,16,97,1,130,76,36.4,A,0,Normal

In [3]:
df = df.drop(columns=['Patient_ID'])
df

,Respiratory_Rate,Oxygen_Saturation,O2_Scale,Systolic_BP,Heart_Rate,Temperature,Consciousness,On_Oxygen,Risk_Level
0,25,96,1,97,107,37.5,A,0,Medium
1,28,92,2,116,151,38.5,P,1,High
2,29,91,1,79,135,38.4,A,0,High
3,24,96,1,95,92,37.3,A,0,Medium
4,20,96,1,97,97,37.4,A,0,Low
...,...,...,...,...,...,...,...,...,...
995,18,96,1,124,72,37.2,A,0,Normal
996,19,95,1,129,70,38.1,A,0,Low
997,39,82,1,101,137,37.5,A,1,High
998,15,92,1,106,108,38.6,A,0,Medium
999,16,97,1,130,76,36.4,A,0,Normal

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Respiratory_Rate   1000 non-null   int64
 1   Oxygen_Saturation  1000 non-null   int64
 2   O2_Scale           1000 non-null   int64
 3   Systolic_BP        1000 non-null   int64
 4   Heart_Rate         1000 non-null   int64
 5   Temperature        1000 non-null   float64
 6   Consciousness      1000 non-null   object
 7   On_Oxygen          1000 non-null   int64
 8   Risk_Level         1000 non-null   object
dtypes: float64(1), int64(6), object(2)
memory usage: 70.4+ KB

In [5]:
df.describe()

,Respiratory_Rate,Oxygen_Saturation,O2_Scale,Systolic_BP,Heart_Rate,Temperature,On_Oxygen
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,21.511000,92.59000,1.124000,106.160000,98.460000,37.921000,0.274000
std,5.287517,4.47302,0.329746,17.897562,19.694626,1.113696,0.446232
min,12.000000,74.00000,1.000000,50.000000,60.000000,35.600000,0.000000
25%,17.000000,90.00000,1.000000,94.000000,84.000000,37.100000,0.000000
50%,20.000000,94.00000,1.000000,109.000000,95.500000,37.800000,0.000000
75%,25.000000,96.00000,1.000000,119.000000,109.000000,38.600000,1.000000
max,40.000000,100.00000,2.000000,146.000000,163.000000,41.800000,1.000000

In [19]:
df = pd.read_csv('Health_Risk_Dataset.csv')
df

,Patient_ID,Respiratory_Rate,Oxygen_Saturation,O2_Scale,Systolic_BP,Heart_Rate,Temperature,Consciousness,On_Oxygen,Risk_Level
0,P0522,25,96,1,97,107,37.5,A,0,Medium
1,P0738,28,92,2,116,151,38.5,P,1,High
2,P0741,29,91,1,79,135,38.4,A,0,High
3,P0661,24,96,1,95,92,37.3,A,0,Medium
4,P0412,20,96,1,97,97,37.4,A,0,Low
...,...,...,...,...,...,...,...,...,...,...
995,P0107,18,96,1,124,72,37.2,A,0,Normal
996,P0271,19,95,1,129,70,38.1,A,0,Low
997,P0861,39,82,1,101,137,37.5,A,1,High
998,P0436,15,92,1,106,108,38.6,A,0,Medium
999,P0103,16,97,1,130,76,36.4,A,0,Normal

In [20]:
df = df.drop(columns=['Patient_ID'])
df

,Respiratory_Rate,Oxygen_Saturation,O2_Scale,Systolic_BP,Heart_Rate,Temperature,Consciousness,On_Oxygen,Risk_Level
0,25,96,1,97,107,37.5,A,0,Medium
1,28,92,2,116,151,38.5,P,1,High
2,29,91,1,79,135,38.4,A,0,High
3,24,96,1,95,92,37.3,A,0,Medium
4,20,96,1,97,97,37.4,A,0,Low
...,...,...,...,...,...,...,...,...,...
995,18,96,1,124,72,37.2,A,0,Normal
996,19,95,1,129,70,38.1,A,0,Low
997,39,82,1,101,137,37.5,A,1,High
998,15,92,1,106,108,38.6,A,0,Medium
999,16,97,1,130,76,36.4,A,0,Normal

In [21]:
print(df["On_Oxygen"].unique())
print(df["On_Oxygen"].dtype)

[0 1]
int64

In [26]:
df["On_Oxygen"] = df["On_Oxygen"].astype(bool)
df

,Respiratory_Rate,Oxygen_Saturation,O2_Scale,Systolic_BP,Heart_Rate,Temperature,Consciousness,On_Oxygen,Risk_Level
0,25,96,1,97,107,37.5,A,False,Medium
1,28,92,2,116,151,38.5,P,True,High
2,29,91,1,79,135,38.4,A,False,High
3,24,96,1,95,92,37.3,A,False,Medium
4,20,96,1,97,97,37.4,A,False,Low
...,...,...,...,...,...,...,...,...,...
995,18,96,1,124,72,37.2,A,False,Normal
996,19,95,1,129,70,38.1,A,False,Low
997,39,82,1,101,137,37.5,A,True,High
998,15,92,1,106,108,38.6,A,False,Medium
999,16,97,1,130,76,36.4,A,False,Normal

In [27]:
df['O2_Scale'].value_counts()

O2_Scale
1    876
2    124
Name: count, dtype: int64

In [28]:
df["O2_Scale"] = df["O2_Scale"].map({1: False, 2: True}).astype(bool)
df

,Respiratory_Rate,Oxygen_Saturation,O2_Scale,Systolic_BP,Heart_Rate,Temperature,Consciousness,On_Oxygen,Risk_Level
0,25,96,False,97,107,37.5,A,False,Medium
1,28,92,True,116,151,38.5,P,True,High
2,29,91,False,79,135,38.4,A,False,High
3,24,96,False,95,92,37.3,A,False,Medium
4,20,96,False,97,97,37.4,A,False,Low
...,...,...,...,...,...,...,...,...,...
995,18,96,False,124,72,37.2,A,False,Normal
996,19,95,False,129,70,38.1,A,False,Low
997,39,82,False,101,137,37.5,A,True,High
998,15,92,False,106,108,38.6,A,False,Medium
999,16,97,False,130,76,36.4,A,False,Normal

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Respiratory_Rate   1000 non-null   int64
 1   Oxygen_Saturation  1000 non-null   int64
 2   O2_Scale           1000 non-null   bool
 3   Systolic_BP        1000 non-null   int64
 4   Heart_Rate         1000 non-null   int64
 5   Temperature        1000 non-null   float64
 6   Consciousness      1000 non-null   object
 7   On_Oxygen          1000 non-null   bool
 8   Risk_Level         1000 non-null   object
dtypes: bool(2), float64(1), int64(4), object(2)
memory usage: 56.8+ KB

In [30]:
print(df["Consciousness"].unique())
print(df["Consciousness"].dtype)

['A' 'P' 'V' 'U' 'C']
object

In [31]:
list(df['Consciousness'].unique())

df['Consciousness'] = df['Consciousness'].map({'A': 1, 'P': 2, 'V': 3, 'U': 4, 'C': 5})
df

,Respiratory_Rate,Oxygen_Saturation,O2_Scale,Systolic_BP,Heart_Rate,Temperature,Consciousness,On_Oxygen,Risk_Level
0,25,96,False,97,107,37.5,1,False,Medium
1,28,92,True,116,151,38.5,2,True,High
2,29,91,False,79,135,38.4,1,False,High
3,24,96,False,95,92,37.3,1,False,Medium
4,20,96,False,97,97,37.4,1,False,Low
...,...,...,...,...,...,...,...,...,...
995,18,96,False,124,72,37.2,1,False,Normal
996,19,95,False,129,70,38.1,1,False,Low
997,39,82,False,101,137,37.5,1,True,High
998,15,92,False,106,108,38.6,1,False,Medium
999,16,97,False,130,76,36.4,1,False,Normal

In [33]:
df['Consciousness'] = df['Consciousness'].astype('category')
df

,Respiratory_Rate,Oxygen_Saturation,O2_Scale,Systolic_BP,Heart_Rate,Temperature,Consciousness,On_Oxygen,Risk_Level
0,25,96,False,97,107,37.5,1,False,Medium
1,28,92,True,116,151,38.5,2,True,High
2,29,91,False,79,135,38.4,1,False,High
3,24,96,False,95,92,37.3,1,False,Medium
4,20,96,False,97,97,37.4,1,False,Low
...,...,...,...,...,...,...,...,...,...
995,18,96,False,124,72,37.2,1,False,Normal
996,19,95,False,129,70,38.1,1,False,Low
997,39,82,False,101,137,37.5,1,True,High
998,15,92,False,106,108,38.6,1,False,Medium
999,16,97,False,130,76,36.4,1,False,Normal

In [34]:
print(df["Risk_Level"].unique())
print(df["Risk_Level"].dtype)

['Medium' 'High' 'Low' 'Normal']
object

In [35]:
list(df['Risk_Level'].unique())

df['Risk_Level'] = df['Risk_Level'].map({'Normal': 1, 'Low': 2, 'Medium': 3, 'High': 4}).astype('category')
df

,Respiratory_Rate,Oxygen_Saturation,O2_Scale,Systolic_BP,Heart_Rate,Temperature,Consciousness,On_Oxygen,Risk_Level
0,25,96,False,97,107,37.5,1,False,3
1,28,92,True,116,151,38.5,2,True,4
2,29,91,False,79,135,38.4,1,False,4
3,24,96,False,95,92,37.3,1,False,3
4,20,96,False,97,97,37.4,1,False,2
...,...,...,...,...,...,...,...,...,...
995,18,96,False,124,72,37.2,1,False,1
996,19,95,False,129,70,38.1,1,False,2
997,39,82,False,101,137,37.5,1,True,4
998,15,92,False,106,108,38.6,1,False,3
999,16,97,False,130,76,36.4,1,False,1

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Respiratory_Rate   1000 non-null   int64
 1   Oxygen_Saturation  1000 non-null   int64
 2   O2_Scale           1000 non-null   bool
 3   Systolic_BP        1000 non-null   int64
 4   Heart_Rate         1000 non-null   int64
 5   Temperature        1000 non-null   float64
 6   Consciousness      1000 non-null   category
 7   On_Oxygen          1000 non-null   bool
 8   Risk_Level         1000 non-null   category
dtypes: bool(2), category(2), float64(1), int64(4)
memory usage: 43.5 KB

In [41]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

In [42]:
df.info(memory_usage = 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Respiratory_Rate   1000 non-null   int64
 1   Oxygen_Saturation  1000 non-null   int64
 2   O2_Scale           1000 non-null   bool
 3   Systolic_BP        1000 non-null   int64
 4   Heart_Rate         1000 non-null   int64
 5   Temperature        1000 non-null   float64
 6   Consciousness      1000 non-null   category
 7   On_Oxygen          1000 non-null   bool
 8   Risk_Level         1000 non-null   category
dtypes: bool(2), category(2), float64(1), int64(4)
memory usage: 43.5 KB

In [44]:
df['Respiratory_Rate'] = df['Respiratory_Rate'].astype('int16')
df['Oxygen_Saturation'] = df['Oxygen_Saturation'].astype('int16')
df['Systolic_BP'] = df['Systolic_BP'].astype('int16')
df['Heart_Rate'] = df['Heart_Rate'].astype('int16')

df['Temperature'] = df['Temperature'].astype('float32')

df.info(memory_usage = 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Respiratory_Rate   1000 non-null   int16
 1   Oxygen_Saturation  1000 non-null   int16
 2   O2_Scale           1000 non-null   bool
 3   Systolic_BP        1000 non-null   int16
 4   Heart_Rate         1000 non-null   int16
 5   Temperature        1000 non-null   float32
 6   Consciousness      1000 non-null   category
 7   On_Oxygen          1000 non-null   bool
 8   Risk_Level         1000 non-null   category
dtypes: bool(2), category(2), float32(1), int16(4)
memory usage: 16.2 KB